### ISSUE TITLE
"java.io.IOException: Connection closed by peer before sending a response" when using a timeout on the Observable

### ISSUE THREAD

**Issue by Crystark** [ReactiveX/RxNetty#436]
Hi,

I'm currently using rxnetty as a proxy server as explained in issue #405.
Lately, I wanted to add a global timeout on this service:

``` java
...
            .compose(myTransformer) // This does some filtering and may return a ProxyResponse early to avoid the call to the final endpoint
            .switchIfEmpty(
                content.compose(o -> finalEndpoint.submit(uri, o))
            )
            .timeout(TIMEOUT, TimeUnit.MILLISECONDS, Observable.just(TIMEOUT_RESPONSE))
            .flatMap(proxyResponse -> {
                response.setStatus(proxyResponse.status);
                if (proxyResponse.headers != null) {
                    for (Entry<String, String> header : proxyResponse.headers) {
                        response.getHeaders().add(header.getKey(), header.getValue());
                    }
                }
                return proxyResponse.content
                    .map(ByteBuf::retain)
                    .<Void> map(bb -> {
                        response.write(bb);
                        return null;
                    });
            })
...
```

Adding this gets me the following error on our canary but I don't seem to be able to reproduce it on our dev server.

```
java.io.IOException: Connection closed by peer before sending a response.
        at io.reactivex.netty.protocol.http.client.ClientRequestResponseConverter.<clinit>(ClientRequestResponseConverter.java:91)
        at io.reactivex.netty.protocol.http.client.ClientRequiredConfigurator.configureNewPipeline(ClientRequiredConfigurator.java:42)
        at io.reactivex.netty.pipeline.PipelineConfiguratorComposite.configureNewPipeline(PipelineConfiguratorComposite.java:55)
        at io.reactivex.netty.pipeline.PipelineConfiguratorComposite.configureNewPipeline(PipelineConfiguratorComposite.java:55)
        at io.reactivex.netty.client.RxClientImpl$2.initChannel(RxClientImpl.java:127)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelRegisteredNow(ChannelHandlerInvokerUtil.java:32)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRegistered(DefaultChannelHandlerInvoker.java:50)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:114)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:833)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:417)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:477)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

Am I doing something wrong with the timeout ?  Is there some other way to set up a timeout  ? My main concern is to have a timeout on the service but I thought I could apply it to the whole proxy server as all in all that's what i'd like to do.

Thanks

**Comment by NiteshKant** [comment]
The exception you mentioned, you are seeing on the client connecting to the proxy server, i.e.

```
Client -> Proxy -> Origin
```

You are seeing the error in the Client above?

**Comment by Crystark** [comment]
@NiteshKant No i'm seeing these errors on the proxy server itself.

**Comment by NiteshKant** [comment]
Ok so looks like the origin closed the connection before your timeout triggered.

**Comment by Crystark** [comment]
I'll close this as I can't get more details about it and changes done to the code (removing the timeout) made it disappear. I'll reopen this if things evolve in that way.

**Comment by Crystark** [comment]
It seems I'm getting this exact same error in a non proxy environment.
I'm using Hystrix with timeouts to do an HTTP call.

How does RxNetty handle the fact the request has been started but its response observable is unsubscribed from before onNext is called ? Could this leak the response ByteBuf ? Could this lead to some race condition ? 

I wonder if there's any chance `Connection closed by peer before sending a response.` could be generated due to this cause it seems tied to the use of timeouts (and thus early unsubscribes).

**Comment by NiteshKant** [comment]
RxNetty should close the channel and cleanly release all unused buffers. If it does not, it is a bug but without a reproducer it is really hard to see where the problem could be.

**Comment by Crystark** [comment]
Ok, so I've created this gist: https://gist.github.com/Crystark/245ee10bf00a2724f229

I can't reproduce the "Connection closed by peer" error but this shows a leak 100% of the time.
If you comment line 51 (`.timeout(15, TimeUnit.MILLISECONDS)`) then no leak occurs.

Can you tell me if I'm doing something wrong or if there indeed is a problem ?
Thanks!

**Comment by NiteshKant** [comment]
Thanks @Crystark for the repro, I can reproduce it locally. Quick look at the access record, it looks like the leak is somehow happening in the `HTTPObjectAggregator`. I will dig more into this.

**Comment by Crystark** [comment]
Have you had time to look into this ?

**Comment by NiteshKant** [comment]
@Crystark yes I did look into it and started working on a PR but got distracted. 
The issue here is that [`UnicastContentSubject`](https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty/src/main/java/io/reactivex/netty/protocol/http/UnicastContentSubject.java) does not release the buffers if the subscriber unsubscribes before termination. 

If you are interested in working on a fix, it will be awesome :)

**Comment by Crystark** [comment]
@NiteshKant I sadly do not have enough time to spare to work on this :( let me know if you get the time to resume the work on the PR. I'd be interested in understanding how  [UnicastContentSubject](https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty/src/main/java/io/reactivex/netty/protocol/http/UnicastContentSubject.java) works cause it's still a bit obscure to me.

**Comment by Crystark** [comment]
@NiteshKant I was going through your fork and i noticed #466 that seems very similar to what we're talking about here. Did you test my code on that fixed version ? I don't have the means to do it at the moment but I thought I'd ask as you were able to reproduce the problem with the code I provided.

**Comment by NiteshKant** [comment]
@Crystark you are rite, #466 will add the timeout for every request and I didn't use the fixed version (duhh outdated forks). I checked it now and there is no leak with the fixed version.

**Comment by Crystark** [comment]
@NiteshKant awesome news ! Any plans to release soon ? ;)

**Comment by NiteshKant** [comment]
I am working on a fix for #474 and should be able to release this week.

**Comment by Crystark** [comment]
This has been fixed in 0.4.16 ! Thanks alot !

**Comment by mkmainali** [comment]
I also hit the same issue. I upgraded my version to 0.4.16 but I still see this issue. Any idea on which versions of dependencies (netty, http-codec etc.) should we use for this one?
