### ISSUE TITLE
0.4.x WebSocketClientServerTest testMessageAggregationOnClient failure

### ISSUE THREAD

**Issue by brharrington** [ReactiveX/RxNetty#463]
I occasionally see a failure for testMessageAggregationOnClient. It also seems to happen pretty reliably on travis. It looks like the failure occurs when the frames the server is sending to the client are received at the same time as the handshake response. When it fails I see:

```
    SEVERE: [id: 0x03e41a02, /127.0.0.1:48559 => localhost/127.0.0.1:35359] RECEIVED: 153B
             +-------------------------------------------------+
             |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
    +--------+-------------------------------------------------+----------------+
    |00000000| 48 54 54 50 2f 31 2e 31 20 31 30 31 20 53 77 69 |HTTP/1.1 101 Swi|
    |00000010| 74 63 68 69 6e 67 20 50 72 6f 74 6f 63 6f 6c 73 |tching Protocols|
    |00000020| 0d 0a 75 70 67 72 61 64 65 3a 20 77 65 62 73 6f |..upgrade: webso|
    |00000030| 63 6b 65 74 0d 0a 63 6f 6e 6e 65 63 74 69 6f 6e |cket..connection|
    |00000040| 3a 20 55 70 67 72 61 64 65 0d 0a 73 65 63 2d 77 |: Upgrade..sec-w|
    |00000050| 65 62 73 6f 63 6b 65 74 2d 61 63 63 65 70 74 3a |ebsocket-accept:|
    |00000060| 20 41 67 43 4c 74 2f 4b 73 43 65 2b 4b 47 35 4e | AgCLt/KsCe+KG5N|
    |00000070| 59 62 31 32 66 61 51 50 36 65 69 6b 3d 0d 0a 0d |Yb12faQP6eik=...|
    |00000080| 0a 01 0a 30 31 32 33 34 35 36 37 38 39 80 0a 41 |...0123456789..A|
    |00000090| 42 43 44 45 46 47 48 49 4a                      |BCDEFGHIJ       |
    +--------+-------------------------------------------------+----------------+
```

When it succeeds it looks like:

```
SEVERE: [id: 0x871313e9, /127.0.0.1:63690 => localhost/127.0.0.1:63688] RECEIVED: 129B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 31 30 31 20 53 77 69 |HTTP/1.1 101 Swi|
|00000010| 74 63 68 69 6e 67 20 50 72 6f 74 6f 63 6f 6c 73 |tching Protocols|
|00000020| 0d 0a 75 70 67 72 61 64 65 3a 20 77 65 62 73 6f |..upgrade: webso|
|00000030| 63 6b 65 74 0d 0a 63 6f 6e 6e 65 63 74 69 6f 6e |cket..connection|
|00000040| 3a 20 55 70 67 72 61 64 65 0d 0a 73 65 63 2d 77 |: Upgrade..sec-w|
|00000050| 65 62 73 6f 63 6b 65 74 2d 61 63 63 65 70 74 3a |ebsocket-accept:|
|00000060| 20 78 71 57 6b 4f 6e 64 54 4c 74 41 75 6b 43 42 | xqWkOndTLtAukCB|
|00000070| 6f 45 31 71 32 6e 39 74 62 45 30 59 3d 0d 0a 0d |oE1q2n9tbE0Y=...|
|00000080| 0a                                              |.               |
+--------+-------------------------------------------------+----------------+
Jan 08, 2016 4:26:20 PM io.netty.handler.logging.LoggingHandler channelRead
SEVERE: [id: 0x871313e9, /127.0.0.1:63690 => localhost/127.0.0.1:63688] RECEIVED: 24B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 01 0a 30 31 32 33 34 35 36 37 38 39 80 0a 41 42 |..0123456789..AB|
|00000010| 43 44 45 46 47 48 49 4a                         |CDEFGHIJ        |
+--------+-------------------------------------------------+----------------+
```

I can make it succeed reliably by adding a flush before sending the client frames:

``` java
   252                  @Override
   253                  public Observable<Void> handle(final ObservableConnection<WebSocketFrame, WebSocketFrame> connection) {
   254                      connection.flush();
   255                      if (clientFrames == null) {
   256                          return sendBatchOfFrames(connection, serverFrames);
   257                      }
```

I think the actual problem is that some of the data can be dropped when the pipeline is reconfigured after the handshake.

**Comment by NiteshKant** [comment]
@brharrington It looks like the issue is because of this netty issue: https://github.com/netty/netty/issues/4635 which is fixed but not yet released.

**Comment by brharrington** [comment]
I tried using 4.1.0.CR1 which has the netty fix mentioned and I'm still seeing failures for this test case. Some other tests occasionally fail as well:

```
$ cat travis.log | grep FAILED
io.reactivex.netty.protocol.http.server.UnexpectedErrorsTest > testErrorHandlerReturnsNull FAILED
io.reactivex.netty.protocol.http.server.UnexpectedErrorsTest > testConnectionHandlerReturnsError FAILED
io.reactivex.netty.protocol.http.websocket.WebSocketClientServerTest > testMessageAggregationOnClient FAILED
:rxnetty:test FAILED
BUILD FAILED
```

From another run:

```
$ cat travis2.log | grep FAILED
io.reactivex.netty.protocol.http.server.UnexpectedErrorsTest > testErrorHandlerReturnsNull FAILED
io.reactivex.netty.protocol.http.websocket.WebSocketClientServerTest > testMessageAggregationOnClient FAILED
:rxnetty:test FAILED
BUILD FAILED
```
